Texts={
	eng={
		but={
			main={"Start","Shop","Settings","Help","Statistics","Quit",},
			mode={"Standard","Entertaining","Back",},
			stage={"Tutorial","Normal","Hard","Endless","E.A.S.I.","Back",},
			entertain={
				"Sprint","Snake","Pool","Float","Piano",
				"Back",
			},
			shop={
				"<",">","^","v",
				function()return data.skinAmount[list]<0 and skinUnlockPrice[list].."□ to unlock" or skinPrice[list].."□/"..skinNum[list].."Cube"end,
				function()return list==data.skinS and sel==data.skinT and"Equipped"or"Equip"end,
				"Back",
			},
			setting={
				function()return setting.sfx and"Disable SFX"or"Enable SFX"end,
				function()return setting.bgm and"Disable BGM"or"Enable BGM"end,
				function()return setting.fullscreen and"Disable Fullscreen"or"Enable Fullscreen"end,
				"Switch language",
				function()return"Mouse sensitive:"..setting.mouseK end,
				function()return"Keyboard sensitive:"..setting.keyboardK end,
				"Back",
			},
			help={"Back"},
			stat={"Back"},
		},
		tutorial={
			"Welcome!",
			"Move with mouse/WASD/Arrows",
			"The only thing you should do is collecting the yellow coins",
			"The shade tell you the position of the next",
			"Faster,combo bar higher,more score!",
			"Fill the orange bar to get an extra life!",
			"Left click to revive,right click to restart",
			"Don't touch the red laser below!",
			"And don't touch the red cross either!",
			"Avoid any dangerous things else!",
			"Left click/space to use skill",
			"Tutorial Finished!",
		},
		easi={[0]="Welcome","Section 1:Erase","Section 2:Agony","Section 3:Simulacrum","Section 4:Ignite",ac="COMING SOON",deadLine="TIME UP",},
		vs={"Mouse","Keyboard"},
		piano="Choose the blue block to play duet!",
		show={cool="Cool!",nice="Nice!",life="L I F E + 1",excellent="Excellent!",},
		lowRemain={"10 skins remain","3 skins remain",},
		gameover={"GAME OVER","--->Restart","Revive<---  --->Restart",},
		shop={remain="Remain:",inf="∞"},
		skinName={"Classic","Random","Glass","More Reds","Aurora","Orient","MC","Strange","War","Art","Costly","Black","Drink","Crystle","Technology","Book","Transparent",},
		skillText={
			na="No skill",
			inv="Invicibility",
			tp_r="Teleport randomly",
			tp_f="Teleport forward",
			tp_h="Teleport back",
			flip="Flip speed",
			freeze="Speed=0",
			eager="Speed to coin",
			slow="Slow time",
			magnet="Absorb coins",
			shield="Get a shield",
			portal="P0rtals",
			back="Flash back",
			atg="Reverse gravity",
			dbl="Double coins",
			boost="Boost energy",
			elife="Extra life",
			miss="75% miss",
		},
		help={
			"This is a hard game about jumping block.",
			"Collect the coins and avoid dangerous things!",
			"Mouse(Arrow/WASD)-Move  Click(Space)-Revive/Skill  Right Click(Z)-Restart",
			"Programmed:MrZ  SFX:MrZ  BGM:MrZ",
			"Art:MrZ/EXY  Design:MrZ/liern",
			"Author:MrZ   Email:1046101471@qq.com",
		},
		stat={"Games played:","Game time:","Total coins collected:","Total block used:",},
		unlock={hard="Hard mode unlocked",easi="EASI mode unlocked",inf="Endless mode unlocked",game1="Entertaining mode unlocked",},
		allclear_h={
			"Good.",
			"",
			"Hard mode finished.",
			"Total game time:&time.",
			"You did it!",
			"However,this is not the end.",
			"Try to complete E.A.S.I. mode.",
			"",
			"Congratulations.",
		},
		load={"Loading textures","Loading BGM","Loading SFX","Finished",},
		tip={
			"You can use mouse and keyboard at the same time!",
			"Hit near the laser twice to upgrade the shield!",
			"The bouncy ability of the ceiling and ground is different!",
			"Use headphone to get better experience!",
			"Press mouse wheel=Esc!",
			"Look!Two players in the sky!",
			"Gravity of the blackhole is also \"gravity\"!",
			"Author hate play this game with keyboard",
			"Bump=Block jump!",
			"",
		},
		anykey="Any action to continue",
	},
	chi={
		but={
			main={"开始","商店","设置","帮助","统计","退出",},
			mode={"标准","娱乐","返回",},
			stage={"教程","普通","困难","无尽","E.A.S.I.","返回",},
			entertain={
				"竞速","贪吃蛇","水池","漂浮","钢琴",
				"返回",
			},
			shop={
				"<",">","^","v",
				function()return data.skinAmount[list]<0 and skinUnlockPrice[list].."块解锁" or skinPrice[list].."块"..skinNum[list].."个"end,
				function()return list==data.skinS and sel==data.skinT and"已使用"or"使用"end,
				"返回",
			},
			setting={
				function()return setting.sfx and"关闭音效"or"打开音效"end,
				function()return setting.bgm and"关闭背景音乐"or"打开背景音乐"end,
				function()return setting.fullscreen and"窗口游戏"or"全屏游戏"end,
				"切换语言",
				function()return"鼠标灵敏度:"..setting.mouseK end,
				function()return"键盘灵敏度:"..setting.keyboardK end,
				"返回",
			},
			help={"返回"},
			stat={"返回"},
		},
		tutorial={
			"欢迎来到BUMP!",
			"鼠标/方向键/WASD 移动",
			"在这个游戏，你的目标是收集黄色的金币",
			"阴影指示了下一个金币出现的位置",
			"吃得越快，连击条越高，分数越高!",
			"把上面的橙色条填满获得额外生命",
			"左键复活，右键重玩",
			"不要碰下面的激光!",
			"也不要碰那个红色的狙击镜!",
			"不要碰到任何有危险的东西!",
			"左键/空格 使用技能",
			"教程结束!",
		},
		easi={[0]="欢迎","第一节：枪决","第二节：尖刺","第三节：映像","第四节：点燃",ac="即将到来",deadLine="时间到",},
		vs={"鼠标","键盘"},
		piano="选择蓝色方块开始二重奏！",
		show={cool="好!",nice="优秀!",life="生命 + 1",excellent="不错!",},
		lowRemain={"10 剩余","3 剩余",},
		gameover={"游 戏 结 束","--->重玩","复活<---  --->重玩",},
		shop={remain="剩余：",inf="∞"},
		skinName={"经典","随机","玻璃","红色","极光","东方","我的世界","奇怪","战争","画","昂贵的","暗","饮料","水晶","科技","书","透明",},
		skillText={
			na="无技能",
			inv="无敌",
			tp_r="随机传送",
			tp_f="向前传送",
			tp_h="定点传送",
			flip="反转速度",
			freeze="静止",
			eager="转向硬币",
			slow="时间减速",
			magnet="吸附金币",
			shield="随时间得到保护罩",
			portal="传送门",
			back="回溯",
			atg="反转重力",
			dbl="双倍金币",
			boost="双倍能量",
			miss="3/4概率闪避",
			elife="一条额外生命",
		},
		help={
			"欢迎来到BUMP，一个极限方块跳跃游戏。",
			"收集金币，其它的东西尽量都不要碰!",
			"鼠标(方向键/WASD)－移动  左键空格)－复活/技能  右(Z)－重玩",
			"程序:MrZ  音效:MrZ  背景音乐:MrZ",
			"美术:MrZ/EXY  设计:MrZ/离新",
			"作者:MrZ   邮箱:616617884@qq.com",
		},
		stat={"游戏局数:","游戏时间:","收集金币数:","方块使用个数:",},
		unlock={hard="困难模式已解锁",easi="EASI模式已解锁",inf="无尽模式已解锁",game1="娱乐模式已解锁",},
		allclear_h={
			"祝贺。",
			"困难模式 完成",
			"你做到了",
			"总游戏时间：&time",
			"玩得不错",
			"不过，这还没有结束。",
			"尝试通关EASI模式吧。欢迎。",
			"",
			"恭喜。",
		},
		load={"加载材质","加载BGM中","加载音效中","加载完成",},
		tip={
			"你可以键盘鼠标一起用!",
			"踩在激光的边缘可以升级护盾!",
			"四面墙的弹力是不一样的！",
			"戴上耳机获得更佳体验！",
			"鼠标滚轮=esc键！",
			"天上有另一个方块！",
			"黑洞的重力也是重力！",
			"作者讨厌用键盘玩这个游戏",
			"",
		},
		anykey="按任意键继续",
	},
}